/*
MIT License

Copyright (c) 2025 groboclown

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/


// In-memory ELF execution stub
// Extracts the blob stored in the header (generated by the make file),
// decompresses it using zlib DEFLATE, then executes that.

// Blind use of zlib causes the stub to add 700k of wrapping bloat
// on top of the compressed executable.  So instead this
// uses the tinf library (https://github.com/jibsen/tinf),
// optimized with exactly the operation it needs.

#define _GNU_SOURCE
#include <sys/mman.h>

#include <unistd.h>
#include <sys/syscall.h>
#include <stdlib.h>
#include <stdio.h>
#include "stub-run.h"

// DietLibC has some issues with the above includes, so we need to include them manually.
#ifndef SYS_memfd_create
#define SYS_memfd_create 319
#endif


int run_embedded(unsigned char *data, unsigned int dataLen, int argc, char *argv[], char *envp[]) {
    // 1) Create an anonymous in-memory file via memfd_create()
    int fd = syscall(SYS_memfd_create, "payload_memfd", MFD_CLOEXEC);
    if (fd < 0) { return 60; }

    // 2) Write the decompressed data to the memfd
    if (write(fd, data, dataLen) != (ssize_t)dataLen) {
        return 61;
    }

    // 3) Rewind the memfd
    if (lseek(fd, 0, SEEK_SET) < 0) {
        return 62;
    }

    // 4) Execute the in-memory ELF
    //    fexecve(2) is GNU extension; glibc wrapper available.
    //    If this returns, then that means the execution failed.
    fexecve(fd, argv, envp);

    // Only ever reaches here if the fexecve failed.
    return 63;
}
