/*
MIT License

Copyright (c) 2025 groboclown

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/


// In-memory ELF execution stub
// Extracts the blob stored in the header (generated by the make file),
// decompresses it using zlib DEFLATE, then executes that.

// Blind use of zlib causes the stub to add 700k of wrapping bloat
// on top of the compressed executable.  So instead this
// uses the tinf library (https://github.com/jibsen/tinf),
// optimized with exactly the operation it needs.

#define _GNU_SOURCE
#include <sys/mman.h>

#include <unistd.h>
#include <sys/syscall.h>
#include <stdlib.h>
#include <stdio.h>

#include "tinf.h"
#include "presh_payload.h"
//unsigned char ___out_presh_bin_deflate[] = { '\00' };
//unsigned int ___out_presh_bin_deflate_len = 1;

#define LAUNCHER_ERROR_LEN 17
char LAUNCHER_ERROR[] = "Launcher failed.\n";

int main(int argc, char *argv[], char *envp[]) {
    int ret;

    unsigned int destSize = ___presh_len;
    unsigned char *dest = malloc(destSize);
    if (!dest) {
        write(STDERR_FILENO, LAUNCHER_ERROR, LAUNCHER_ERROR_LEN);
        return 1;
    }
    ret = tinf_uncompress(dest, &destSize, ___presh_z, ___presh_z_len);
    if (ret < 0) {
        write(STDERR_FILENO, LAUNCHER_ERROR, LAUNCHER_ERROR_LEN);
        return 1;
    }
    if (ret != TINF_OK) {
        write(STDERR_FILENO, LAUNCHER_ERROR, LAUNCHER_ERROR_LEN);
        return 1;
    }

    // 1) Create an anonymous in-memory file via memfd_create()
    int fd = syscall(SYS_memfd_create, "payload_memfd", MFD_CLOEXEC);
    if (fd < 0) {
        write(STDERR_FILENO, LAUNCHER_ERROR, LAUNCHER_ERROR_LEN);
        return 1;
    }

    // 2) Write the decompressed data to the memfd
    if (write(fd, dest, destSize) != (ssize_t)destSize) {
        write(STDERR_FILENO, LAUNCHER_ERROR, LAUNCHER_ERROR_LEN);
        return 1;
    }

    // 3) Rewind the memfd
    if (lseek(fd, 0, SEEK_SET) < 0) {
        write(STDERR_FILENO, LAUNCHER_ERROR, LAUNCHER_ERROR_LEN);
        return 1;
    }

    // 4) Execute the in-memory ELF
    //    fexecve(2) is GNU extension; glibc wrapper available.
    if (fexecve(fd, argv, envp) < 0) {
        write(STDERR_FILENO, LAUNCHER_ERROR, LAUNCHER_ERROR_LEN);
        return 1;
    }

    // Should never reach here
    return 0;
}
