name: Build
on:
  # Trigger the workflow on pushes to only the 'master' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [main, dev]
  # Trigger the workflow on any pull request
  pull_request:

jobs:

  glibc-ubuntu:
    name: Build & Test with glibc on Ubuntu
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      #  .. and setup an ipv6 container network so that the
      #     commands that use it work as expected.
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      # Setup an ipv6 container network so that the
      #     commands that use it work as expected.
      - name: Setup Network
        run: |
          podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1
          podman network ls
          podman network inspect podnet1

      - name: build-test
        run: |
          podman build --network=podnet1 -f build-glibc.Dockerfile -t glibc:offline --build-arg COMMANDS=ALL .
      # Podman on Ubuntu is a buggy version that causes this to look up the
      # image online, rather than look in the local repo.
      # https://github.com/containers/podman/issues/11181
      # podman images
      # ./extract-executables.sh localhost/glibc:offline -o out/glibc
      # ls -lA out/glibc
     
      - name: cmd-test
        run: |
          podman build --network=podnet1 -f build-glibc.Dockerfile -t glibc:offline --build-arg BUILD_MODE=individual-cmd-test .
      
      - name: file-size
        run: |
          podman build --network=podnet1 -f build-glibc.Dockerfile -t glibc:offline --build-arg BUILD_MODE=cmd-size .

  glibc-arch:
    name: Build & Test with glibc on Arch Linux
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1 || echo "podnet1 already exists"
          podman build --network=/home/runner/.config/cni/net.d/podnet1.conflist -f build-glibc-arch.Dockerfile -t glibc-arch:offline --build-arg COMMANDS=ALL .
      # Podman on Ubuntu is a buggy version that causes this to look up the
      # image online, rather than look in the local repo.
      # https://github.com/containers/podman/issues/11181
      # podman images
      # ./extract-executables.sh localhost/glibc:offline -o out/glibc
      # ls -lA out/glibc
     
      - name: cmd-test
        run: |
          podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1 || echo "podnet1 already exists"
          podman build --network=podnet1 -f build-glibc-arch.Dockerfile -t glibc-arch:offline --build-arg BUILD_MODE=individual-cmd-test .
      
      - name: file-size
        run: |
          podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1 || echo "podnet1 already exists"
          podman build --network=podnet1 -f build-glibc-arch.Dockerfile -t glibc-arch:offline --build-arg BUILD_MODE=cmd-size .

  musl:
    name: Build & Test with musl
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      #  .. and setup an ipv6 container network so that the
      #     commands that use it work as expected.
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1 || echo "podnet1 already exists"
          podman build --network=podnet1 -f build-musl.Dockerfile -t musl:offline --build-arg COMMANDS=ALL .
      
      - name: cmd-test
        run: |
          podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1 || echo "podnet1 already exists"
          podman build --network=podnet1 -f build-musl.Dockerfile -t musl:offline --build-arg BUILD_MODE=individual-cmd-test .
      
      - name: file-size
        run: |
          podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1 || echo "podnet1 already exists"
          podman build --network=podnet1 -f build-musl.Dockerfile -t musl:offline --build-arg BUILD_MODE=cmd-size .

  dietlibc:
    name: Build & Test with dietlibc
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      #  .. and setup an ipv6 container network so that the
      #     commands that use it work as expected.
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1 || echo "podnet1 already exists"
          podman build --network=podnet1 -f build-dietlibc.Dockerfile -t dietlibc:offline --build-arg COMMANDS=ALL .

      - name: cmd-test
        run: |
          podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1 || echo "podnet1 already exists"
          podman build --network=podnet1 -f build-dietlibc.Dockerfile -t dietlibc:offline --build-arg BUILD_MODE=individual-cmd-test .

      - name: file-size
        run: |
          podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1 || echo "podnet1 already exists"
          podman build --network=podnet1 -f build-dietlibc.Dockerfile -t dietlibc:offline --build-arg BUILD_MODE=cmd-size .


  sample:
    name: Run the sample builds.
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          podman build -t local/precision-shell-sample --build-arg FLAGS=INCLUDE_ALL_COMMANDS=1 .
          podman run --rm -t local/precision-shell-sample version


  recipes:
    name: Ensure the recipes build and work as expected.
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          CONTAINER_RUNNER=podman recipes/_build_all.sh
          CONTAINER_RUNNER=podman recipes/tests/run_all.sh
