name: GitActions-IPv6-Test
on:
  push:
    branches: [manual]

jobs:
  # This is to test out a bug report to Git Actions.
  try-podman-ipv6:
    name: Run podman with ipv6 network
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: Run Failing Podman
        run: |
          cd /tmp
          mkdir test-ipv6
          echo 'FROM docker.io/library/alpine:3.10' > Dockerfile
          sudo podman network create --ipv6 --subnet=fd00:0bca:85f3:17a0::/64 podnet1
          sudo podman build --network podnet1 -t test-ipv6:local .
